---
- hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: upgrade all packages
      yum:
        name: '*'
        state: latest
    - name: Ensure OpenJDK
      yum:
        name: java-1.8.0-openjdk-headless
        state: latest
